server:
  port: 8084

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
    
queue:
  movie:
    name: Movie

info:
  app:
    name: movie-service
    description: Movie Service created for Class 12 Examen Parcial
    version: 1.0.0
