server:
  port: 8084

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3308/dhStreaming
    username: user
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver
    
queue:
  movie:
    name: Movie

info:
  app:
    name: movie-service
    description: Movie Service created for Class on DH
    version: 1.0.0
