server:
  port: 8086

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      host: mongodb
      port: 27017
      database: dhStreamingseries

queue:
  serie:
    name: Serie

    
info:
  app:
    name: serie-service
    description: Serie Service created for Class on DH
    version: 1.0.0
